# Generated by Django 3.2.5 on 2022-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tittle', models.CharField(max_length=50)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('blog_description', models.CharField(max_length=200)),
            ],
        ),
    ]
