# Generated by Django 3.2.5 on 2022-03-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
