# Generated by Django 3.2.20 on 2024-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='detected_violence_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='violence_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
