# Generated by Django 3.2.5 on 2022-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tittle', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('blog_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
