# Generated by Django 3.2.5 on 2022-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_tittle', models.CharField(max_length=100)),
                ('material_file', models.FileField(blank=True, null=True, upload_to='study_material/')),
                ('material_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
